### ISSUE TITLE
Inconsistent property naming on interfaces

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/consumer_api_contracts#15]
#### Describe your issue

I noticed there are cases where the property names of some interfaces use snake case instead of camelCase.

See https://github.com/process-engine/consumer_api_contracts/blob/develop/src/data_models/process_model/process_start_request_payload.ts

I didn't look into all files, but there might be more places affected, so all interfaces in contracts should be checked.

Since the Consumer API is not fully used by other libraries yet, it would be a good opportunity to fix them now, before dozens of usages have to be refactored.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/132

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/133
