### ISSUE TITLE
Add token payload and EndEvent to ProcessStartResponse

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/consumer_api_contracts#25]
Relates to: https://github.com/process-engine/consumer_api_core/issues/35

#### Describe your issue

Currently the `ProcessStartResponsePayload` only contains the correlation id.

It should also contain the token payload for the EndEvent reached to resolve the request.

#### Possible solution

Proposed data structure for the `ProcessStartResponsePayload`:

```
{
   correlationId: string;
   endEventId?: string;
   tokenPayload?: any; 
}
```

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/171
