### ISSUE TITLE
Refactor correlation result

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/consumer_api_contracts#26]
Relates to: https://github.com/process-engine/consumer_api_core/issues/36

#### Describe your issue

The current `ICorrelationResult` doesn't contain any information on what EndEvents have been reached and what the specific token payload for each EndEvent was.

#### Possible solution

The future `ICorrelationResult` should contain a list of all EndEvents that can be viewed by the identity. For each EndEvent the token payload needs to be contained as well.

This should be implemented in the same format as https://github.com/process-engine/consumer_api_contracts/issues/25.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/171
