### ISSUE TITLE
🐛 Define consumer-api objects

### ISSUE THREAD

**Issue by heikomat** [process-engine/consumer_api_contracts#5]
#### Describe your issue

A lot of objects on the consumer-api are currently placeholder-defined by setting them to any.
These objectTypes need to get well defined.

These objects are:
- [Event](https://github.com/process-engine/consumer_api_contracts/blob/7fdd9441ad5ae0b5f77f892c37e19770c591d445/src/ievent.ts)
- [EventTriggerPayload](https://github.com/process-engine/consumer_api_contracts/blob/7fdd9441ad5ae0b5f77f892c37e19770c591d445/src/ievent_trigger_payload.ts)
- [ProcessModel](https://github.com/process-engine/consumer_api_contracts/blob/7fdd9441ad5ae0b5f77f892c37e19770c591d445/src/iprocess_model.ts)
- [UserTask](https://github.com/process-engine/consumer_api_contracts/blob/7fdd9441ad5ae0b5f77f892c37e19770c591d445/src/iuser_task.ts)
- [UserTaskResult](https://github.com/process-engine/consumer_api_contracts/blob/7fdd9441ad5ae0b5f77f892c37e19770c591d445/src/iuser_task_result.ts)

#### How can others reproduce the issue?

You'll see that you don't have intellisense for these objects

#### Possible solution

Define these ObjectTypes.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
Closed, in favour of: https://github.com/process-engine/consumer_api_contracts/issues/9 (Because everything beside the EventTriggerPayload is done)
